archives:
- id: archive
  name_template: '{{ .Binary }}-{{ .Tag }}-{{ .Os }}-{{ .Arch }}-via-{{ .Env.GO_VERSION }}-{{ .Env.BUILD_PLATFORM }}'
builds:
- binary: go-dns-test-via-{{ .Env.GO_VERSION }}-{{ .Env.BUILD_PLATFORM }}
  env:
  - CGO_ENABLED=0
  - GO111MODULE=on
  goarch:
  - amd64
  - arm64
  goos:
  - darwin
  - linux
  main: ./cmd/go-dns-test.go
changelog:
  skip: true
release:
  disable: false
snapshot:
  name_template: '{{ .Tag }}-SNAPSHOT'
checksum:
  name_template: 'checksums-{{ .Env.GO_VERSION }}-{{ .Env.BUILD_PLATFORM }}.txt'
