env:
  IS_PRERELEASE: "true"
jobs:
  publish:
    name: publish
    runs-on: ${{ matrix.build-platform }}
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
    - name: Unshallow clone for tags
      run: git fetch --prune --unshallow --tags || true
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.goversion }}
        stable: false
    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v2
      with:
        args: release -p 10 --timeout 60m0s --skip-publish
        version: latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GO_VERSION: go${{ matrix.goversion }}
        BUILD_PLATFORM: ${{ matrix.build-platform }}
    - name: Publish intermediate artifacts for linux / amd64
      uses: actions/upload-artifact@v2
      with:
        name: dist-linux-amd64-via-${{ matrix.goversion }}-${{ matrix.build-platform }}
        path: |
         dist/go-dns-test_linux_amd64/*
    - name: Publish intermediate artifacts for linux / arm64
      uses: actions/upload-artifact@v2
      with:
        name: dist-linux-arm64-via-${{ matrix.goversion }}-${{ matrix.build-platform }}
        path: |
         dist/go-dns-test_linux_arm64/*
    - name: Publish intermediate artifacts for darwin / amd64
      uses: actions/upload-artifact@v2
      with:
        name: dist-darwin-amd64-via-${{ matrix.goversion }}-${{ matrix.build-platform }}
        path: |
         dist/go-dns-test_darwin_amd64/*
    - name: Publish intermediate artifacts for darwin / arm64
      uses: actions/upload-artifact@v2
      with:
        name: dist-darwin-arm64-via-${{ matrix.goversion }}-${{ matrix.build-platform }}
        path: |
         dist/go-dns-test_darwin_arm64/*
    strategy:
      fail-fast: false
      matrix: # this is the build platform matrix
        include:
          - goversion: 1.18.0-beta2 # does not include patch
            build-platform: ubuntu-latest
          - goversion: 1.18.0-beta2 # does not include patch
            build-platform: macos-latest
          - goversion: 1.18.0-rc1 # includes DNS patch
            build-platform: ubuntu-latest
  release:
    name: release
    needs: [publish]
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          path: dist
      - name: List artifacts
        run: ls -laR dist
    strategy:
      fail-fast: false
      matrix: # this is the target platform matrix
        include:
          - arch: amd64
            os: linux
            os-synonym: linux
          - arch: arm64
            os: linux
            os-synonym: linux
          - arch: amd64
            os: macos
            os-synonym: darwin
          - arch: arm64
            os: macos
            os-synonym: darwin
name: publish
"on":
  push:
    tags:
    - v*.*.*
    - v*.*.*-**
    branches:
    - main
